version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
    volumes:
        - pgdata:/data/postgres
    networks:
      backend:
        ipv4_address: 172.23.0.2


  app:
    build: .
    depends_on:
      - database_ignite
    container_name: rentx
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      -  backend
    

volumes:
  pgdata:
    driver: local


networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.2/24